mapf98/api-bodenchufe

modules/authentication/authentication.router.js
modules/setting/setting.controller.js
modules/setting/setting.model.js
modules/setting/setting.router.js

**NOTA**: esta es la plantilla para indicar los aspectos importantes de un PULL REQUEST. 
Por favor, llenar los campos necesarios y eliminar comentarios antes de publicar (incluida esta nota).
Se agrega al modulo de settings la funcionalidad de obtener los parámetros generales de la aplicación
FASE1-073
[Consultar Parámetros Generales](https://trello.com/c/0uoEpavx/159-consultar-par%C3%A1metros-generales)
_Añade las nuevas características que han sido implementadas (los más(+) representan un item dentro de una lista)_
+ Característica 1: Se agrego el modulo para consultar los parámetros generales de la aplicación
+ Característica 2: Se obtiene los parámetros de la comisión del procesador de pago y la comisión de servicio por los momentos.
_Relata todo lo referente a nuevas dependencias, …

FASE1-073 Se agregó el modulo de consulta de parametros generales

---

config/db_scripts/insert.sql
modules/category/category.controller.js
modules/category/category.model.js
modules/category/category.router.js

Esta es la tarea correspondiente a la obtención de categorías con sus respectivas categorías hijo de manera recursiva.
Esta PR va asociado a la [FASE1-071](https://trello.com/c/bwVoGEAN/153-consultar-categor%C3%ADas)
Esta tarea también cumple un criterio de aceptación de la [FASE1-058](https://trello.com/c/y2ko1It2/131-agregar-publicaci%C3%B3n)
+ Se implementó una función para obtener las categorías recursivamente.
+ Se construyó un JSON de respuesta para la consulta de las categorías y sus asociadas.

FASE1-071: Consultar Categorías

---

modules/product/product.controller.js
modules/product/product.model.js
modules/product/product.router.js

Se agrego la consulta de productos en base a una categoría.
Esta tarea responde a [FASE1-002](https://trello.com/c/yONJFzLV/165-b%C3%BAsqueda-filtrada-de-productos-por-categor%C3%ADas)
Esta tarea corresponde a los criterios de aceptación de las siguientes tareas:
+ [FASE1-016](https://trello.com/c/sMSNpT0q/177-navegaci%C3%B3n-entre-categor%C3%ADas)
+ [FASE1-017](https://trello.com/c/KKDIlCGL/179-visualizar-los-productos-de-la-b%C3%BAsqueda)
+ Obtener los productos relacionados a una categoría

FASE1-002 Se obtienen productos en base a una categoría

---

modules/user/user.controller.js
modules/user/user.model.js
modules/user/user.router.js

Con esta función se le permite al cliente poder modificar la cantidad de productos que tiene en su carrito de compras
[Modificar cantidad del carrito](https://trello.com/c/4OUDdpBb/205-modificar-cantidad-del-carrito)
+ Característica 1: Se puede modificar la cantidad de productos del carrito.
+ Característica 2: Se valida que la nueva cantidad no exceda a la disponible en inventario.

FASE1-022 Modificar la cantidad de productos agregados al carrito

---

modules/user/user.controller.js
modules/user/user.model.js
modules/user/user.router.js

Se le permite al cliente poder eliminar los productos no deseados de su carrito de compras
FASE1-023
[Eliminar productos del carrito](https://trello.com/c/wyYOdKPL/207-eliminar-productos-del-carrito)
+ Característica 1: se permite al cliente eliminar productos de su carrito.

FASE1-023 Eliminar productos del carrito de compras

---

config/db_scripts/create.sql
config/db_scripts/insert.sql
modules/category/category.controller.js
modules/category/category.model.js
modules/category/category.router.js
modules/coupon/coupon.controller.js
modules/coupon/coupon.model.js
modules/coupon/coupon.router.js
modules/offer/offer.controller.js
modules/offer/offer.model.js
modules/offer/offer.router.js
modules/product/product.controller.js
modules/product/product.model.js
modules/product/product.router.js
modules/provider/provider.controller.js
modules/provider/provider.model.js
modules/provider/provider.router.js
modules/user/user.controller.js
modules/user/user.model.js
modules/user/user.router.js

Actualización de la rama master con los cambios actuales

Actualización de la rama master con los últimos cambios (4/5/2020)

---

config/db_scripts/create.sql
config/db_scripts/insert.sql
modules/product/product.model.js

Este pull request responde a cambios que consiguieron necesarios después de analizar el envío de los productos.
[FASE1-004](https://trello.com/c/rXOVwBKg/169-visualizaci%C3%B3n-de-la-pantalla-de-bienvenida-del-e-commerce) y [FASE1-002](https://trello.com/c/yONJFzLV/165-b%C3%BAsqueda-filtrada-de-productos-por-categor%C3%ADas)
+ Se estructuró el query para tomar en cuenta los elementos necesarios que deben tener los productos al ser consultados.

FASE1 FIX-002-004: Cambios en la búsqueda de productos por oferta, categoría y proveedor.

---

config/db_scripts/create.sql
config/db_scripts/insert.sql
modules/delivery_address/delivery_address.controller.js
modules/delivery_address/delivery_address.model.js
modules/delivery_address/delivery_address.router.js
modules/user/user.controller.js
modules/user/user.model.js
modules/user/user.router.js

Con este PR se permite al cliente poder consultar sus direcciones de entrega.
También se permite poder consultar las direcciones de entrega de todos los clientes del sistema.
[Consultar direcciones de entrega](https://trello.com/c/yjt7AQIy/64-ver-direcciones-de-entrega)
+ Característica 1: se permite consultar las direcciones de entrega de todos los clientes.
+ Característica : se un cliente puede consultar sus propias direcciones de entrega

FASE1-025 Consulta de direcciones de envio

---

modules/authentication/authentication.controller.js
modules/authentication/authentication.model.js
modules/authentication/authentication.router.js

Se agrega la funcionalidad para iniciar sesión en la aplicación
FASE1-010 [Inicio de sesión no federado](https://trello.com/c/oX7RwiFO/194-inicio-de-sesi%C3%B3n-no-federado)
Fases asociadas:
FASE1-008 [Inicio de sesión federado con Google](https://trello.com/c/EYyAQmFK/189-inicio-de-sesi%C3%B3n-federado-con-google)
FASE1-009 [Inicio de sesión federado con Facebook](https://trello.com/c/n5O5hb6w/191-inicio-de-sesi%C3%B3n-federado-con-facebook)
FASE1-040 [Ver información del usuario](https://trello.com/c/2rwmIHl9/73-ver-informaci%C3%B3n-de-usuario)
FASE1-046 [Inicio de sesión bloqueado](https://trello.com/c/gUOeEHwM/81-inicio-de-sesi%C3%B3n-bloqueado)
FASE1-049 [Inicio de sesión Administrador](https://trello.com/c/4rYqK1Au/84-inicio-de-sesi%C3%B3n-administrador)
+ Se accede a la aplicación …

Fase1 010: Inicio de sesión

---

modules/order/order.controller.js
modules/order/order.model.js
modules/order/order.router.js

Consulta de todos los pedidos y sus datos asociados para vista de administración.
Hace referencia a la HU [FASE1-062](https://trello.com/c/UbsgTQnE/121-consultar-pedidos)
Consulta de ordenes con:
+ Estatus
+ Proveedor
+ Precio de producto en publicación con cantidad en pedido
+ Fecha y todos los datos relevantes en la orden

FASE1-062 Consulta de todas las ordenes dentro del sistema para BackOffice

---

modules/authentication/authentication.controller.js
modules/order/order.controller.js
modules/order/order.model.js
modules/order/order.router.js
modules/provider/provider.controller.js
modules/provider/provider.model.js
modules/provider/provider.router.js

El objetivo principal fue para agregar proveedores.
Se realizaron unos arreglos en la búsqueda de ordenes y el módulo de authentication.
En la rama se trabajó sobre [FASE1-054](https://trello.com/c/Otv8Nile/123-agregar-proveedores)
Se hicieron unos arreglos sobre [FASE1-062](https://trello.com/c/UbsgTQnE/121-consultar-pedidos)
+ Agregar un nuevo proveedor al sistema

FASE1-054 Agregar un nuevo proveedor, arreglos menores en los módulos de order y authentication.

---

config/db_scripts/insert.sql
modules/order/order.controller.js
modules/order/order.model.js
modules/user/user.router.js

Este PR cumple las actividades de la FASE1-034 , 036 y 037.
Se le permite al usuario poder consultar todas sus ordenes de compra y el detalle de la orden de compra.
Esto servirá para poder consultar las ordenes por año, por status, entre otros.
FASE1-034
[Historial de pedidos procesados](https://trello.com/c/j8DWBKsg/68-ver-historial-de-pedidos-procesados)
FASE1-036
[Historial de pedidos por año](https://trello.com/c/nFeduXgG/70-visualizar-pedidos-por-a%C3%B1o)
FASE1-037
[Ver productos asociados a una orden](https://trello.com/c/Vu8ULgmO/71-ver-productos-asociados-a-un-pedido)
+ Característica 1: el cliente podra consultar sus ordenes de compra
+ Característica 2: se muestra por cada orden de compra, el detalle de la misma, la cual incluye todo los productos comprados y las cantidades.

FASE1-034-036-037 Ordenes de compra y detalle de orden de un cliente

---

modules/authentication/authentication.controller.js
modules/authentication/authentication.model.js
modules/user/user.controller.js
package-lock.json
package.json
utils/Email.js

Con este PR se habilita la opción de poder mandar correos a los usuarios de la plataforma.
Se implemento Sendgrid y se realizo el envío de correo de bienvenida para los usuarios.
HU FASE1-012
[Correos de bienvenida](https://trello.com/c/gbakszCV/78-correo-de-bienvenida-a-nuevos-usuarios)
+ Característica 1: se implemento la herramienta Sendgrid para habilitar el envío de correos.
+ Característica 2: se realizo el envío de correo de bienvenida al momento del registro.
Se instalo la libreria de Sendgrid

FASE1-012 Envio de correos con sendgrid y correo de bienvenida

---

config/db_scripts/insert.sql
modules/authentication/authentication.controller.js
modules/user/user.controller.js
modules/user/user.model.js
modules/user/user.router.js

Propósito 📑
Con este PR se agrega la funcionalidad de que el usuario pueda desactivar su cuenta.
HU FASE1-043 
[Desactivar cuenta de usuario](https://trello.com/c/Ynu0lu9V/77-deshabilitar-cuenta-por-el-usuario)
+ Característica 1: el usuario puede desactivar su cuenta si asi lo desea.

FASE1-043  Desactivación de cuenta por parte del usuario

---

modules/order/order.controller.js
modules/user/user.controller.js
modules/user/user.model.js
modules/user/user.router.js

Este PR permite a los usuarios administradores poder activar y bloquear cuentas de usuarios.
Este PR cumple las tareas de las HU
FASE1-051 [Activar cuentas bloqueadas](https://trello.com/c/MlGumWGs/115-activar-cuentas-bloqueadas)
FASE1-052 [Bloquear cuentas](https://trello.com/c/TsQYtIMu/118-bloqueo-de-sesi%C3%B3n-administrador)
+ Característica 1: se permite al administrador la activación de cuentas bloqueadas.
+ Característica 2: se permite al administrador  bloquear alguna cuenta de usuario.

FASE1-051-052 Bloqueo y activación de cuentas por el administrador

---

middlewares/auth.js
modules/authentication/authentication.controller.js
modules/authentication/authentication.model.js
modules/user/user.router.js

Se implemento el manejo de roles y privilegios para garantizar el acceso a usuarios únicamente a los recursos que están autorizados.
Roles a trabajar: user, administrator

FASE1-ROLES/PRIVILEGIOS Manejo de roles y privilegios

---

modules/authentication/authentication.controller.js
modules/user/user.controller.js
modules/user/user.model.js
modules/user/user.router.js

Con este PR se le permite al usuario poder editar su información personal y cambiar de contraseña
FASE1-041 
[Editar información del usuario](https://trello.com/c/NqkFKNhD/74-editar-informaci%C3%B3n-de-usuario)
+ Característica 1: el usuario podrá editar su información personal
+ Característica 2: el usuario podrá editar su contraseña

FASE1-041 Modificación de datos de usuario y cambio de contraseña

---

modules/order/order.model.js
modules/product/product.controller.js
modules/product/product.model.js
modules/user/user.router.js

En este PR se implemento la función para que el usuario pueda calificar un producto que haya comprado.
HU FASE1-038
[Calificar los productos de un pedido](https://trello.com/c/fIa5VaEq/63-calificar-los-productos-de-un-pedido)
+ Característica 1: el usuario puede calificar productos.
+ Característica 2: solo se pueden calificar productos que haya comprado.

FASE1-038 Calificar producto comprado

---

modules/language/language.controller.js
modules/language/language.router.js
package.json
router.js
utils/POEditor.js

Se creó el módulo language para poder lidiar con el cambio de idioma a través de POEditor.
Este PR responde a la historia de usuario [FASE1-003](https://trello.com/c/Ympz3b6M/167-selecci%C3%B3n-del-idioma-del-e-commerce).
+ Se implementó la conexión con POEditor desde la API.
+ Se solicita la información referente a los términos definidos en POEditor dependiendo del idioma seleccionado por el usuario (junto con sus traducciones).
+ Se transforma la data proveniente de POEditor para su manejo adecuado en el FE.
+ Se añadió el paquete axios para poder realizar peticiones a POEditor.

FASE1-003: Internacionalización a través de POEditor.

---

config/db_scripts/create.sql
modules/authentication/authentication.model.js
modules/coupon/coupon.model.js
modules/order/order.controller.js
modules/order/order.model.js
modules/payment/payment.controller.js
modules/user/user.model.js
utils/Email.js

Se realiza el envío de correos cuando la transacción del pago haya sido confirmada en la blockchain.
HU FASE1-032
[Recibir correo al confirmar pago](https://trello.com/c/3UK363ZG/79-recibir-un-recibo-de-pago-al-correo)
+ Característica 1: cuando el pago haya sido confirmado en la blockchain, se le notifica al cliente  a través de un correo.

FASE1-032 Envio de correo de la confirmación del pago

---

config/logLevels.js
modules/product/product.controller.js
modules/product/product.model.js
modules/product/product.router.js

Se creó una ruta para la búsqueda de productos o categorías mediante un keyword.
Este pull request responde a la HU [FASE1-001](https://trello.com/c/qaxyHD0s/160-b%C3%BAsqueda-filtrada-de-productos-por-palabras-clave)
+ Listado de productos y categorías en base a un keyword.

FASE1-001: Búsqueda de productos o categorías mediante un searchbox.

---

modules/authentication/authentication.controller.js
modules/authentication/authentication.model.js
modules/authentication/authentication.router.js
modules/category/category.controller.js
modules/delivery_address/delivery_address.controller.js
modules/setting/setting.model.js
modules/user/user.controller.js
modules/user/user.model.js

Se modifica el modelo de usuario al mostrar los cupones de un usuario en específico
+ Se devuelve el status en el que el cupón se encuentra (disponible o no disponible)

Fix-general-coupon-errors
